### ISSUE TITLE
Clarify/Update recommended node.js version to 10.12.0?

### ISSUE THREAD

**Issue by sadohert** [mattermost/mattermost-developer-documentation#678]
I was having an issue trying to build `mattermost-mobile` `master` branch (as of today, commit:1bba361f8976ffce80ac108e4cc0ee55349320f6).  There were errors like:

```
TypeError: Failed to load plugin 'mattermost' declared in '.eslintrc.json': createRequire is not a function
Referenced from: /Users/stu/development/mattermost-mobile/.eslintrc.json
```

I looked at the ESLint version I was running (I believe `7.4.0`) and it [documented](https://www.npmjs.com/package/eslint/v/7.4.0) these versions for node ^10.12.0, or >=12.0.0.

In our docs [here](https://developers.mattermost.com/contribute/mobile/developer-setup/#install-nodejshttpsnodejsorgen) we say 10.11.0.  

After I updated to 10.12 the build completed successfully.

If there's some historical mapping on older `mattermost-mobile` versions and what version of nodethey require, maybe we create a table with the mapping by Mattermost release version.

**Comment by haardikdharma10** [comment]
Hi @sadohert, Your issue seems related/similar to #350.
